apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.backend.name}}
  namespace: {{.Values.namespace}}
data:
  PORT: "{{.Values.backend.port}}"
  DB_HOST: "{{.Values.db.name}}" #database service name
  DB_DIALECT: "mysql"