apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.db.name}}"
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.db.replicas}}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{.Values.db.name}}"
  template:
    metadata:
      labels:
        app: "{{.Values.db.name}}"
    spec:
      containers:
      - name: "{{.Values.db.name}}"
        image: "{{.Values.db.image.name}}:{{.Values.db.image.tag}}"
        ports:
        - containerPort: {{.Values.db.port}}
        envFrom:
        - secretRef:
            name: {{.Values.secret.name}}
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: {{.Values.pvc.name}}
