apiVersion: v1
kind: Service
metadata:
  name: "{{ include "jdmapp.fullname" . }}-{{.Values.db.name}}"
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: "{{.Values.db.name}}"
  ports:
  - protocol: TCP
    port: {{.Values.db.port}}
    targetPort: {{.Values.db.port}}
  type: ClusterIP