apiVersion: v1
kind: Service
metadata:
  name: "{{ include "jdmapp.fullname" . }}-{{.Values.frontend.name}}"
  namespace: {{.Values.namespace}}
  labels:
    {{- include "jdmapp.labels" . | nindent 4 }}
spec:
  selector:
    app: "{{ include "jdmapp.fullname" . }}-{{.Values.frontend.name}}"
  ports:
  - protocol: TCP
    port: {{.Values.frontend.port}}
    targetPort: {{.Values.frontend.port}}
  type: LoadBalancer