apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "jdmapp.fullname" . }}-{{.Values.frontend.name}}"
  namespace: {{.Values.namespace}}
data:
  REACT_APP_BACKEND_URL: "{{.Values.backend.service.name}}:{{.Values.backend.port}}"