apiVersion: v1
kind: Service
metadata:
  name: "{{ include "jdmapp.fullname" . }}-{{ .Values.frontend.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    app: "{{ include "jdmapp.fullname" . }}-{{ .Values.frontend.name }}"
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  type: LoadBalancer