# filepath: /home/ronaldo/Documentos/GitHub/jdm-cars-app/k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "jdmapp.fullname" . }}-{{.Values.frontend.name}}"
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ include "jdmapp.fullname" . }}-{{.Values.frontend.name}}"
            port:
              number: {{.Values.frontend.port}}