apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  #DATABASE_URL: {{ printf "mysql://root:example@%s:3306/jdm_cars" .Values.db.name | b64enc }}
  #DATABASE_URL: {{ printf "mysql://root:example@%s:3306/jdm_cars" (include "jdmapp.fullname" . | printf "%s-%s" .Values.db.name) | b64enc }}
  DATABASE_URL: {{ printf "mysql://root:example@%s:3306/jdm_cars" (printf "%s-%s" (include "jdmapp.fullname" .) .Values.db.name) | b64enc }}
  MYSQL_DATABASE: {{ "jdm_cars" | b64enc }}
  MYSQL_PASSWORD: {{ "app_password" | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ "example" | b64enc }}
  MYSQL_USER: {{ "app_user" | b64enc }}