permissions:
  contents: write

name: Update Helm Chart

on:
  repository_dispatch:
    types:
      - update-helm-chart

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Chart repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update image tags in values.yaml
        run: |
          sed -i "/frontend:/,/replicas:/s|^\s*tag:.*|tag: ${{ github.event.client_payload.frontend_tag }}|" jdmapp/values.yaml
          sed -i "/backend:/,/replicas:/s|^\s*tag:.*|tag: ${{ github.event.client_payload.backend_tag }}|" jdmapp/values.yaml
          sed -i "/db:/,/port:/s|^\s*tag:.*|tag: ${{ github.event.client_payload.db_tag }}|" jdmapp/values.yaml


      - name: Update version and appVersion in Chart.yaml
        run: |
          # Actualizar version del chart
          sed -i "s/^version:.*/version: 0.1.${{ github.run_number }}/" jdmapp/Chart.yaml
          # Actualizar appVersion con los tags de las imágenes (por simplicidad se puede usar el tag frontend, o ajustar si querés)
          sed -i "s/^appVersion:.*/appVersion: \"frontend: ${{ github.event.client_payload.frontend_tag }}, backend: ${{ github.event.client_payload.backend_tag }}, db: ${{ github.event.client_payload.db_tag }}\"/" jdmapp/Chart.yaml

      - name: Package Helm Chart
        run: helm package jdmapp

      - name: Publish Helm Chart
    
        run: |
          mv jdmapp-*.tgz docs/
          helm repo index docs/ --url https://ronaldorodriguezbermudez.github.io/helm-chart-app/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add jdmapp/values.yaml jdmapp/Chart.yaml docs/
          git commit -m "Update Helm Chart to version 0.1.${{ github.run_number }} with appVersions updated"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/ronaldorodriguezbermudez/helm-chart-app.git
          git push origin HEAD:main
